// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDSb0a6NtWPqKa3aTJyuBbYEmn2JN_e0',
    appId: '1:380462808341:web:450a698e2e79544bfefd1c',
    messagingSenderId: '380462808341',
    projectId: 'btih-mobile-app',
    authDomain: 'btih-mobile-app.firebaseapp.com',
    storageBucket: 'btih-mobile-app.firebasestorage.app',
    measurementId: 'G-H725J3CG1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvFg_3h8NQsmTzQvmKi-KE-44htVsMOXA',
    appId: '1:380462808341:android:b212476da3ad2cb2fefd1c',
    messagingSenderId: '380462808341',
    projectId: 'btih-mobile-app',
    storageBucket: 'btih-mobile-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCa0-y7TQ8XC-_n6hcrc6PPzitRJDrowk',
    appId: '1:380462808341:ios:c2d8c97e35473bd8fefd1c',
    messagingSenderId: '380462808341',
    projectId: 'btih-mobile-app',
    storageBucket: 'btih-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.btihAndriodApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCa0-y7TQ8XC-_n6hcrc6PPzitRJDrowk',
    appId: '1:380462808341:ios:c2d8c97e35473bd8fefd1c',
    messagingSenderId: '380462808341',
    projectId: 'btih-mobile-app',
    storageBucket: 'btih-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.btihAndriodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDSb0a6NtWPqKa3aTJyuBbYEmn2JN_e0',
    appId: '1:380462808341:web:21201d32cf8177c3fefd1c',
    messagingSenderId: '380462808341',
    projectId: 'btih-mobile-app',
    authDomain: 'btih-mobile-app.firebaseapp.com',
    storageBucket: 'btih-mobile-app.firebasestorage.app',
    measurementId: 'G-M59RNV1DZQ',
  );
}
